source "http://rubygems.org"

gem "rails", "3.0.0.rc"
gem "capybara", ">= 0.3.9"
gem "mysql"

gem 'haml'
gem 'authlogic'

if RUBY_VERSION < '1.9'
  gem "ruby-debug", ">= 0.10.3"
end

gem "rspec-rails", ">= 2.0.0.beta"
gem "rspec"
gem 'factory_girl_rails'
gem 'acts_as_rateable', ">= 2.0.1"
gem 'acts-as-taggable-on'
gem 'hpricot'
